/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.laidelibrary;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class ManageUsers extends javax.swing.JFrame {

    /**
     * Creates new form ManageUsers
     */
    public ManageUsers() {
        initComponents();
        
        //Centralise the Window
        this.setLocationRelativeTo(null);
        
        //Stop the Window Exit Button from closing the application
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAllUsers = new javax.swing.JTable();
        lblAllUsers = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblUpdateUser = new javax.swing.JLabel();
        btnCreateNewUser = new javax.swing.JButton();
        lblUpdateUser1 = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        spnUserID = new javax.swing.JSpinner();
        lblColumnToUpdate = new javax.swing.JLabel();
        cbUpdateColumn = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        txtUpdateValue = new javax.swing.JTextField();
        cbDeleteColumn = new javax.swing.JComboBox<>();
        txDeleteValue = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/laidelibrary/images/laide_library_logo.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(56, 72, 96));
        lblTitle.setText("Manage Users");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator2.setForeground(new java.awt.Color(76, 171, 118));

        tbAllUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbAllUsers);

        lblAllUsers.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblAllUsers.setForeground(new java.awt.Color(56, 72, 96));
        lblAllUsers.setText("All Users");

        jSeparator1.setForeground(new java.awt.Color(76, 171, 118));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        lblUpdateUser.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblUpdateUser.setForeground(new java.awt.Color(56, 72, 96));
        lblUpdateUser.setText("Update User");
        lblUpdateUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnCreateNewUser.setBackground(new java.awt.Color(56, 72, 96));
        btnCreateNewUser.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCreateNewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateNewUser.setText("Create New User");
        btnCreateNewUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewUserActionPerformed(evt);
            }
        });

        lblUpdateUser1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblUpdateUser1.setForeground(new java.awt.Color(56, 72, 96));
        lblUpdateUser1.setText("Delete User");
        lblUpdateUser1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblUserId.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblUserId.setForeground(new java.awt.Color(56, 72, 96));
        lblUserId.setText("User ID:");

        spnUserID.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        spnUserID.setModel(new javax.swing.SpinnerNumberModel());

        lblColumnToUpdate.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblColumnToUpdate.setForeground(new java.awt.Color(56, 72, 96));
        lblColumnToUpdate.setText("Select column to update:");

        cbUpdateColumn.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        cbUpdateColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "FirstName", "LastName", "Age", "Gender", "PhoneNumber", "Address", "State", "MothersMaidenName", "Username", "EmailAddress", "Password", "RoleID" }));

        btnUpdate.setBackground(new java.awt.Color(56, 72, 96));
        btnUpdate.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        cbDeleteColumn.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        cbDeleteColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "UserID", "PhoneNumber", "Username", "EmailAddress" }));
        cbDeleteColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeleteColumnActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(56, 72, 96));
        btnDelete.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(64, 120, 102));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(345, 345, 345))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(357, 357, 357))))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblAllUsers)
                        .addGap(263, 263, 263)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblColumnToUpdate)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUpdateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbUpdateColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txDeleteValue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbDeleteColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(54, 54, 54))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(btnCreateNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUpdateUser)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUserId)
                                .addGap(18, 18, 18)
                                .addComponent(spnUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblUpdateUser1)
                                .addGap(78, 78, 78))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUpdateUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserId)
                            .addComponent(spnUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblColumnToUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbUpdateColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUpdateValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUpdateUser1)
                        .addGap(1, 1, 1)
                        .addComponent(cbDeleteColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txDeleteValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAllUsers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                    .addComponent(jSeparator1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewUserActionPerformed
        // Display the User Registration Form
        UserRegistration_Admin urObject = new UserRegistration_Admin();
        urObject.setVisible(true);
    }//GEN-LAST:event_btnCreateNewUserActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Create an SQLQueries object to check availability of the user in database
        SQLQueries queryObject = new SQLQueries();
            
        // Get the content of the User ID Spinner 
        int userID = (int) spnUserID.getValue();

        // Check that column to be updated is selected
        String column = cbUpdateColumn.getSelectedItem().toString();
        String data = txtUpdateValue.getText();
        
        // pattern for valid firstName, lastName and mothersMaidenName
        Pattern namePattern = Pattern.compile("[A-Za-z]{2,22}");
        
        // pattern for valid email
        Pattern emailPattern
                = Pattern.compile("[a-zA-Z0-9._]+@[a-z]+\\.[a-z]{2,3}");
        
        //the pattern for valid phone number
        Pattern phonePattern = Pattern.compile("0+[7-9]{1}[01]{1}[0-9]{8}");
        
        // pattern for valid password
        Pattern passwordPattern = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=."
                + "*[A-Z])(?=.*[@#$%^&-+=()])(?=\\S+$).{8,20}$");
        
        // matching the text in the fields against their respective patterns
        Matcher firstNameMatcher = namePattern.matcher(data);
        Matcher lastNameMatcher = namePattern.matcher(data);
        Matcher mothersMaidenNameMatcher = 
                namePattern.matcher(data);
        Matcher phoneMatcher = phonePattern.matcher(data);
        Matcher emailMatcher = emailPattern.matcher(data);
        Matcher passwordMatcher = 
                passwordPattern.matcher(data);
        
        try{
        //Confirm that the userID field is not left blank or zero
        if (userID == 0) {
            JOptionPane.showMessageDialog(this,
                    "Please enter UserID!",
                    "Enter UserID!", JOptionPane.WARNING_MESSAGE);
        } else if(column.equals("Select")){
            JOptionPane.showMessageDialog(this,
                    "Please select a column to be updated!",
                    "Select update column!", JOptionPane.WARNING_MESSAGE);
        } else if(data.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the new " + column 
                    + "!", column + " Field is Blank!", 
                    JOptionPane.WARNING_MESSAGE);
            // YOU STILL NEED TO DO REGEX FOR ALL DETAILS!!!
        } else if(column.equals("FirstName") && !firstNameMatcher.matches()){
            JOptionPane.showMessageDialog(this, "Please enter a valid " + column 
                    + "!", "Invalid " + column + "!", 
                    JOptionPane.WARNING_MESSAGE);
        } else if(column.equals("LastName") && !lastNameMatcher.matches()){
            JOptionPane.showMessageDialog(this, "Please enter a valid " + column 
                    + "!", "Invalid " + column + "!", 
                    JOptionPane.WARNING_MESSAGE);
        } else if(column.equals("Age") && Integer.parseInt(data) < 16){
            JOptionPane.showMessageDialog(this, "Please enter a valid " + column 
                    + "!", "Invalid " + column + "!", 
                    JOptionPane.WARNING_MESSAGE);
        } else{
            String userStatus = queryObject.validateUser(userID);
            
            if(userStatus.equals("valid")){
                // If the user exists, update the user's details
                String updateStatus = queryObject.updateUser(userID, column, data);
                if(updateStatus.equals("successful")){
                    JOptionPane.showMessageDialog(this,
                    "Update Successful!", "Success!",
                    JOptionPane.INFORMATION_MESSAGE);
                } else{
                    JOptionPane.showMessageDialog(this,
                        "Unable to update User's Details!",
                        "An error occured!",
                        JOptionPane.ERROR_MESSAGE);
                }     
            } else {
                JOptionPane.showMessageDialog(this,
                        "Please enter a valid User ID!",
                        "Error! Invalid UserID!",
                        JOptionPane.ERROR_MESSAGE);
            }
        }}catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this,
                        "Please enter a valid Age!",
                        "Error! Invalid Age!",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Close this window
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbDeleteColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeleteColumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDeleteColumnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNewUser;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbDeleteColumn;
    private javax.swing.JComboBox<String> cbUpdateColumn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAllUsers;
    private javax.swing.JLabel lblColumnToUpdate;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdateUser;
    private javax.swing.JLabel lblUpdateUser1;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JSpinner spnUserID;
    private javax.swing.JTable tbAllUsers;
    private javax.swing.JTextField txDeleteValue;
    private javax.swing.JTextField txtUpdateValue;
    // End of variables declaration//GEN-END:variables
}
